---
# Start of options to set
report_title: |
  Strait of Georgia Pacific Herring (*Clupea pallasii*) stock update in 2024
assess_yr: "2024"
report_year: "2025"
release_month: "January"
report_number: "XXX"
meeting_date: "September 23, 2024"
region: "Pacific Region"
phone: "(250) 555-5555"
email: "DFO.PacificCSA-CASPacifique.MPO@dfo-mpo.gc.ca"
csa_address: "3190 Hammond Bay Rd., Nanaimo, BC V9T 6N7"
report_title_french: |
  Mise à jour du stock de hareng du Pacifique (*Clupea pallasii*)
  du détroit de Géorgie en 2024
inuktitut_citation: |
  Inuktitut citation here
context: |
  Pacific Herring (*Clupea pallasii*) abundance in British Columbia is assessed
  using a spatially integrated statistical catch at age model fit to
  spawn survey indices, fishery age composition data, and commercial catches.
  This stock assessment evaluates abundance relative to
  the limit reference point, the upper stock reference, and
  fisheries management objectives.
  [...]
  We recommend a management procedure for the
  Strait of Georgia stock assessment region.
output:
 csasdown::fsar_word
link-citations: false
bibliography: bib/refs.bib
csl: csl/csas.csl
# End of options to set
title: ""
knit: (function(input, ...) {
       csasdown::render_sar()
      })
always_allow_html: true
header-includes:
  - \usepackage{pifont}% http://ctan.org/pkg/pifont
  - \newcommand{\xmark}{\ding{55}}%
---

```{r libraries, echo = FALSE, message = FALSE}
# External packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(RColorBrewer)
library(rosettafish)
library(csasdown)
library(here)
library(patchwork)
library(scales)
library(gfutilities)
library(kableExtra)
```

```{r setup, echo = FALSE}
# Set knitr options
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
  kable_format <- "latex"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
  kable_format <- "pandoc"
}
# Set knitr chunk options
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.path = "knitr-figs-docx/",
  fig.asp = 0.618,
  fig.width = 7,
  echo = FALSE,
  dev = "png",
  dpi = 180
)
```

```{r metadata}
# assess_yr <- metadata$assess_yr
assess_yr <- 2024
MSE_yr    <- 2023
# meta_out <- metadata$output
# french <- meta_out$`csasdown::fsar_word`$french
french    <- FALSE
include_extras <- TRUE 

MPname <- "maxTHR_0.14"

# TODO: [SAM] add a list of any variables needed to
# change. i.e. Region, USR, BO, [see functions.R/makeModelHistTable[arguments]]
```

```{r models}

source(here("R", "functions.R"))

# Load all model data.
models_dir <- here("data")
major_stock_dir <- list("SoG")

# first, load model histories
histFolder <- file.path("data","SOG_DDM_omGrid")

fitFolders <- c("fit_parBatSOG_MbhGrid_h.71",
                "fit_parBatSOG_OMgrid_h.70_2",
                "fit_parBatSOG_OMgrid_h.70_3",
                "fit_parBatSOG_OMgrid_h.70_4",
                "fit_parBatSOG_OMgrid_h.70_5")

fitPaths <- here(histFolder, fitFolders, paste0(fitFolders, ".rds"))

histRpts <- lapply(X = fitPaths, FUN = readRDS)

scenarios <- c("SOG_Mb0.532_h0.70",
               "SOG_Mb0.562_h0.65",
               "SOG_Mb0.562_h0.70",
               "SOG_Mb0.562_h0.75",
               "SOG_Mb0.584_h0.70")

wtPosts <- readRDS("data/wtPosts.rds")

names(histRpts) <- scenarios

# order hist reports
histRpts <- histRpts[c(3,2,4,1,5)]

# Now weighted ensemble OMs
simFolder <- file.path("data","SOG_wtdPerf_Ugrid")

# Now read the infoFile in each sim folder
dirList   <- list.dirs(simFolder, recursive = FALSE)
dirList   <- dirList[grepl(x = dirList, pattern = "sim_")]

infoList  <- file.path(dirList,"infoFile.txt")
infoList  <- lapply(X = infoList, FUN = lisread)
infoList  <- lapply(X = infoList, FUN = as.data.frame)
info.df   <- do.call(rbind, infoList)

mps   <- c("Ugrid_0.06","Ugrid_0.14")
mps2  <- c("maxTHR_0.06","maxTHR_0.14")

# Filter info.df for chosen MPs
info.df <- info.df |> filter( mp %in% mps )
mpBlobList <- list()

for(k in 1:nrow(info.df))
{
  simLabel <- paste0("sim_",info.df$simLabel[k])
  path <- file.path(simFolder,simLabel,paste0(simLabel,".RData"))
  # Load blob
  load(path)

  # Save to mpBlobList
  mpBlobList[[k]] <- blob

}
names(mpBlobList) <- mps2

# Pull some model dimensions and year labels
fYear   <- blob$ctlList$opMod$fYear
nS      <- blob$om$nS
nP      <- blob$om$nP
nT      <- blob$om$nT
tMP     <- blob$om$tMP
pT      <- blob$ctlList$opMod$pT

# Labels for automated text generation
species <- blob$om$speciesNames
stock   <- blob$om$stockNames

# Get good reps (should be all there for ensemble)
goodRepIdx <- which(blob$goodRep)

# Draw a random replicate for plotting
set.seed(101)
randReplicate <- sample(goodRepIdx, size = 1)
randTraces    <- sample(goodRepIdx, size = 3)
usePosts      <- blob$ctlList$opMod$posteriorSamples

# Load MP application fit report
fit_maxTHR0.14 <- readRDS("data/fit_maxTHR0.14/fit_maxTHR0.14.rds")
mpFitList <- list(fit_maxTHR0.14)
names(mpFitList) <- MPname

# Load ref pts and ensemble parameters
# SOG ref pts, weighted average from 2023 operating model grid
ensRefPtsTable <- read.csv("data/SOG_ensRefPts.csv") |>
  mutate_if(is.numeric, round, 2)
# SOG model parameters, weighted average from 2023 operating model grid
ensParTable <- read.csv("data/ensOM_meanPars.csv") |>
  mutate_if(is.numeric,round,2) |>
  mutate(PBTGtLRP = ifelse(PBTGtLRP > 0.99, 0.99, .)) # if >.99 set = 0.99 else leave alone
```

```{r scripts}
# Files
source(here("R", "variables.R"))
source(here("R", "figures.R"))
source(here("R", "themes.R"))

# Theme for figures
theme_set(theme_herring())
```

<!-- Math expressions -->
\newcommand{\mli}[1]{\mathit{#1}}
\newcommand{\SB}{\mli{`r en2fr("SB", translate = french)`}}
\newcommand{\BR}{\mli{BR}}
\newcommand{\AVE}{\text{`r en2fr("AVE", translate = french)`}}

<!-- Compile the document on the command line: -->
<!-- csasdown::render_sar() -->
