## BASIS FOR ASSESSMENT {-}


### Assessment Details {-}

This report presents science advice for the Pacific Herring Strait of Georgia 
(SoG) stock assessment region, which is one of the 
`r number_to_word(length(major_regions_short))` major stock areas; the other 
major and the `r number_to_word(length(minor_regions_short))` minor stock
areas are presented in [@dfo2024bInPrep, In Prep.].

SoG Pacific Herring are assessed with a management 
strategy evaluation (MSE) process, which implements a spatially integrated statistical 
catch at age Herring (SISCAH) modelling framework [@dfo2023a]. 
The modelling framework is fitted to historical time series of spawn survey indices, 
biological and fishery age composition data, and commercial fishery catches.

The SISCAH operating model represents SoG Herring historical biomass time series 
from 1951-2003 with these features: density dependent mortality (DDM), an integrated surface 
and dive survey index, gear-specific commercial fishery timing, and a 
likelihood function with correlated age-compositions.
Density dependent natural mortality was added to represent potential ecosystem 
impacts (e.g., depensatory predation) on Pacific Herring stocks in line with
DFO's EAFM (ecosystem approaches to fisheries management).

A weighted ensemble operating model is used for management procedure 
evaluation, containing five different models 
representing a range of productivity levels. Productivity is characterized
by stock recruitment steepness 
($h$), which affects productivity at low stock sizes, and the lower 
limit on natural mortality ($M_b$), which represents the average mortality rate 
at high stock sizes. This chosen approach represents uncertainty in stock 
productivity better than using a single value of stock-recruit steepness,
which is difficult to estimate and often reliant on prior information.
Details of the operating model ensemble are described in Appendix A.

The weighted ensemble OM was used to simulate management procedures (MPs) over a 
15-year projection period (2024-2038) and present a MP tuned to meet 
the conservation objective
(Section "[Fishery management objectives](#sec:fish-mgmt-objs)") and that is
compliant with both the “DFO Sustainable Fisheries Framework” policy and 
“A fishery decision-making framework incorporating the Precautionary Approach”
policy as per the 
[Terms of Reference](https://www.dfo-mpo.gc.ca/csas-sccs/Schedule-Horraire/2024/09_23-eng.html).

#### Year Assessment Approach was Approved {-}

The SISCAH operating model framework implemented here for SoG Herring was 
reviewed and approved by CSAS in June 2023 [@dfo2023a].

#### Assessment Type {-}

<!-- [Mandatory. -->
<!-- Select one of the following: -->
Full assessment, MSE process, with update to the management procedure and harvest control rule.
<!-- Interim Year Update, or -->
<!-- Harvest Decision Rule (HDR) Update. -->
<!-- See the Guidance Document for definitions.]  -->

#### Most Recent Assessment Date {-}

Last Full Assessment: this document (2024).

#### Assessment Approach {-}

1. Broad category: Full MSE process using a single stock operating model ensemble.
<!-- [Select one of the following: -->
<!-- Data-poor (e.g., catch-MSY, very limited data, etc.), -->
<!-- index-based (trends in empirical indices only), -->
<!-- single stock assessment model, -->
<!-- model ensemble, -->
<!-- or MSE-lite), -->
<!-- Wild Salmon Policy Integrated Assessment, -->
<!-- multiple approaches, -->
<!-- other (specify)] -->


2.	Specific category:
<!-- [Select one or as many as apply: -->
<!-- No data, -->
<!-- Index-based (fishery-dependent indices only), -->
<!-- (including fishery-dependent and fishery-independent indices), -->
<!-- Delay difference, -->
<!-- Biomass dynamics, -->
<!-- Virtual population analysis, -->
<!-- Statistical catch-at-length, -->
<!-- Sequential Population Analysis, -->
<!-- Surplus Production, -->
<!-- Potential Biological Removal, -->
<!-- Other (please explain)] -->
Index-based,
state-space,
statistical catch-at-age model, 
with a Beverton-Holt stock-recruitment relationship and
density dependent time varying natural mortality.

<!-- [Optional short summary of stock assessment methodology. -->
<!-- Include the method of considering ecosystem variables. -->
<!-- Include a reference to a Research Document or other publication, -->
<!-- and/or footnote to the working paper. -->
<!-- Maximum length 100 words.] -->

<!-- Mandatory -->
This SISCAH modelling framework [@johnson2024] provides stock status and 
updated MPs with associated quota calculations for the SoG Herring for the 
2024/25 season.

### Stock Structure Assumption {-}
<!--Stock overview information: -->
<!--[reference to a Research Document or other publication, and/or footnote to the working paper] -->
<!--[Mandatory. Maximum length 150 words.]-->

SoG Herring is one of five major Pacific Herring stocks managed in British Columbia. 
The other major and minor stocks are described in [@dfo2024].
The SoG stock spawns primarily in March, over multiple locations 
and with variable timing.
Details of spawn timing and locations are described in the
[2024 SoG data summary report](https://github.com/grinnellm/Reports/blob/master/Summaries/2024/DataSummary.SoG.2024.pdf).
Post spawning, mature SoG Herring
migrate to the west coast Vancouver Island (WCVI) to share share summer/ fall 
feeding grounds with WCVI Herring. However adult Herring are also reported in the 
Salish Sea throughout the summer months indicating some level of non-migratory life
history. New genetic methods are currently being used to update baseline data for SoG
spawning areas which may provide more insight on sub-stock structure in the Salish Sea.

### Reference Points {-}
<!-- [Mandatory. -->
<!-- A table may be used in lieu of bullets for this section. -->
<!-- Refer to the Guidance Document for further instructions.] -->
For Pacific Herring MSE we present a suite of biological and fishery reference 
points as performance metrics for the MP evaluations. 
These are derived as fractions of ${B_0}$ (unfished spawning biomass), 
${MSY}$ (maximum sustainable yield), and $U_{MSY}$ (the harvest rate at ${MSY}$).

<!-- TODO (Sam): I wonder if it would be useful to put the Yield~Spawning biomass
curve for OM1 in here? (to give reader a sense of relative position of LRP and USR-->

#### Limit Reference Point (LRP) {-}

In 2018, a biological limit reference point (LRP) was defined for Pacific
Herring major stocks as $0.3B_0$ in 2018, where ${B_0}$ is the long-term
average estimated unfished spawning biomass ([@kronlund2017], [@forrest2023]).
This LRP is more conservative than the default LRP identified in 
“DFO Sustainable Fisheries Framework” policy [@dfo2009].

#### Upper Stock Reference (USR) {-}

Candidate USRs were first introduced in @cleary2018 and a formal analysis of 
USR options was undertaken in 2022 [@dfo2022a].
Following consultations, DFO Resource Management then selected and implemented 
${0.8B}_{1998:2007}$ as a "provisional USR" for the 2022/23 IFMP 
where the USR was included as a performance metric in the MP evaluations.
Note that the productive period USR was first developed as a spatial proxy
for spawn distribution for WCVI Herring [@cleary2018].
Because consultations are ongoing for SoG Herring USRs, we include 
5 USR performance metrics in this analysis: 
0.8$U_{MSY}$ and all four candidate USRs ($B_{MSY}$ proxies from @dfo2022a).


#### Target Reference Point (TRP) {-}

A biomass target objective centered on the USR has been suggested Within the 
Herring MSE process, however selection of a USR for SoG Herring requires 
additional consultations and thus a TRP is not yet definable.

#### Removal Reference (RR) {-}

The default maximum RR for commercially harvested fish stocks is
$F_{MSY}$ [@dfo2009, @dfo2013].
All MPs presented for Pacific Herring stocks that are shown in simulation to 
avoid the LRP with high probability, and thus meet the conservation objective,
include maximum target harvest rates below $U_{MSY}$.
We do not specify an additional RR for SoG Herring because with MSE we use
simulations to select a MP tuned directly to the conservation objective
(which implements harvest rates more conservative than $U_{MSY}$).

#### Habitat or Ecosystem Reference Points {-}

Ecosystem reference points are incorporated into
the conservation objective for Herring through:

1. A LRP of 0.3${B_0}$ based on an analysis of stock productivity [@kronlund2017]
which is well-above the default LRP of 0.4$B_{MSY}$ [@dfo2009] and 
which is also above the soft-limit of 0.5$B_{MSY}$ implemented in 
New Zealand fisheries [@shelton2008].
The LRP of 0.3${B_0}$ for the ensemble operating model is
approximately 0.7$B_{MSY}$ (Appendix A).

2. Incorporating density dependent mortality to account for predation mortality
to fully represent the trophic level of Herring as a forage species.

### Fishery management objectives {-#sec:fish-mgmt-objs}

A core set of fisheries management objectives [@dfo2019c]
was introduced to the Pacific Herring MSE process in 2019.
The first of these is a conservation objective which is centered on
the LRP.

1. Maintain spawning biomass at or above the LRP with
at least 75% probability over three Pacific Herring generations
(i.e., avoid a biomass limit; $P(\SB_t \geq 0.3 \SB_0) \geq 0.75$).

Three additional proposed objectives are used as performance metrics
for MP evaluation.
These are:

2. Maintain spawning biomass at or above the USR with at least 50% 
probability over three Pacific Herring generations (i.e., achieve a 
target biomass; $P(\SB_t \geq \SB_{targ}) \geq 0.50$),

3. Maintain average annual variability (AAV) in catch below 25% over three
Pacific Herring generations (i.e., minimize catch variability; 
$\text{AAV} < 0.25$), and

4. Maximize average annual catch over three Pacific Herring 
generations (i.e., maximize average catch).

DFO continues to collaborate with coastal First Nations to develop 
area-specific objectives for Indigenous fisheries and 
engage with the Herring industry, government and non-government 
organizations to describe broader objectives related to conservation, 
economics, and access.

### Operating Model Stock Status {-}

Stock status for the SoG aggregate stock is derived from the operating model 
ensemble which represents weighting across five different models each 
representing a range of productivity levels (Appendix [A](#sec:app-a)).
The ensemble model stock status for 2023 is reported in Section 
"[Assessment under MSE](#sec:assessment)"

DFO Science, Pacific Region, will update operating models for SoG Herring 
every three years.
As such, in 2026 the SISCAH model will be fit to new SoG survey and fishery data 
(extending the historical time series) and MPs will be re-evaluated against 
fishery management objectives. 
At this time new objectives and performance metrics may
also be added to the MSE process.

In the interim years (2024 and 2025), operating model status remains constant, 
and a biomass estimate is updated annually and applied to the management 
procedure (next section).

### Harvest Decision Rule {-}

This MSE report presents sustainable harvest advice for SoG Herring using 
simulation tested MPs in which we identify the maximum target harvest rate for 
a MP tuned to the established conservation objective using a 15-year projection
period. 
We also report simulated performance against a suite of other biological and 
fishery reference points, with details described in
Section "[Projections](#sec:projections)".

The harvest control rule component of each simulation-test MP is
a "hockey-stick" shaped function defined by lower and upper control points, and
a maximum target harvest rate [@cox2013roles]. 
We explored two hockey-stick shapes which differed in their lower and upper
control points, and three 3 maximum target harvest rates
(Figure \@ref(fig:plotHCRules)).
Sustainable harvest advice for SoG Herring for 2024/25 is presented using 
a MP tuned to the conservation objective. This MP has lower and upper control 
points at 30\% and 60\% of unfished spawning biomass and a maximum target
harvest ($maxTHR$) of 14\% (green solid line, Figure \@ref(fig:plotHCRules)).

```{r plotHCRules, echo = FALSE, fig.cap = HCRcap, fig.asp = 0.9}
HCRcap <- "Three harvest control rule components of SoG management procedures (MPs). The green line represents the MP tuned to meet the conservation objective over the 15-year projection period for the ensemble operating model (with density dependent natural mortality) and maximum target harvest rate, $maxTHR$, of 14\\%. The red line denotes an additional hockey-stick shaped rule with the previously used 20\\% maximum target harvest rate and the purple line shows the DFO default harvest control rule with maximum target harvest rate set at $U_{MSY}$ and control points at $0.4 \\cdot B_{MSY}$ and $0.8 \\cdot B_{MSY}$."

plotHCRules(  LCP_i = c(.3,.3,.172),
              UCP_i = c(.6,.6,.342),
              lowF = .0,
              highF = 1,
              U_i = c(.14,.20,.187) ,
              language = "English")
```


### Performance Evaluation for Interim Years and Exceptional Circumstances {-}

For each interim stock status 
is estimated using the estimation model component of the MP and this, plus
the survey index and realized catch are compared to the simulation 
envelopes from the ensemble model.
Exceptional circumstances are determined 
by visually comparing catch and spawn index estimates for the new year
with the central 95\% of the ensemble operating model simulations.
Any unusual deviations from the ensemble model projections would be 
investigated in detail and consideration given to refitting operating models.
For example, if the previous year's realized catch far exceeds the TAC 
prescribed by the MP or if the survey index is far below the projected index.

### Data {-}
<!-- [Mandatory. -->
<!-- Maximum length 300 words.]  -->
<!-- Data changes: -->
<!-- [Optional (otherwise, do not include).] -->

There are three types of input data used for
the Pacific Herring stock assessment:
catch data, biological data, and a fishery independent survey index.
The fishery survey index is made up of two classes of surveys, surface
and dive. Combining the surveys into a blended index properly accounts for 
years in which these survey types co-occur and is a feature 
of the new SISCAH model. Note `r assess_yr` refers to the `r this_season`
Pacific Herring season.
