## ASSESSMENT {-}

- Example cross-reference:
Stock status in relation to four indicators (see Figure \@ref(fig:indicators)).

[Mandatory panel of images comes first – example shown.
Refer to the Guidance Document for options and further instructions.]

(ref:indicators-cap) Stock status indicators for Pacific Herring in the Strait of Georgia (SoG) major stock assessment region (SAR) from `r yr_range[1]` to `r yr_range[2]`. (A) Catch (line) and total allowable catch (TAC; dashed line). (B) Spawning stock biomass (SSB) in relation to the limit reference point (LRP; dashed red line) and upper stock reference (USR; dotted green line). (C) Fishing mortality (F; black line), removal reference (RR; dashed red line), and natural mortality (M; dotted line). (D) Recruitment of age-`r age_recruit` fish. Legend: lines indicate median values, grey shading indicates `r ci_pct`% confidence intervals, mortality is per year (yr), biomass is in tonnes (t), and recruitment is number of fish.

```{r indicators, fig.cap = "(ref:indicators-cap)"}
# Four-panel indicator plot
plot_indicators(dat = sim_dat)
```

[Optional. Add an additional optional panel of 4 indicators
if relevant to developing advice.] 
[Optional. If the FSAR or FSRR is being used
to provide advice for more than one stock,
the mandatory panel can be repeated for each stock.]

### Historical and Recent Stock Trajectory and Trends {-}

[Mandatory.
Maximum text length one page.
Must be first section in Assessment section.]

[Report trends in relevant indicator(s), one per paragraph,
in the following format:]

#### [Indicator 1] [specify name, e.g., Abundance]: {-}

[Provide values and trends for the stock (as applicable).]

#### Unknown {-}

[Optional.
Indicate what indicators are not available for the stock (as applicable);
otherwise, do not include.]

### History of [Management; Landings/Harvest/Effort, TAC \& Catch Advice] {-}

[Mandatory.
Title can vary.
Maximum text length one page.] 

Harvest options for `r assess_yr+1` reflect application of
simulation-tested MPs for each major SAR,
derived from the Herring OM [@benson2022]. 
OM conditioning was updated in 2022 using
historic stock and fishery data from `r major_start_yr` to 2021;
no MP updates were conducted for 2023.
MPs are not provided for HG because this is now conducted within the 
HG rebuilding plan process.$^{\ref{fn:rebuild}}$

<!-- #### History of Hatchery and Supplementation {-} -->

<!-- [If applicable (otherwise, do not include).] -->

<!-- #### History of Freshwater Habitat Impacts {-} -->

<!-- [If applicable (otherwise, do not include).] -->

### Projections [optional titles: Simulations, Future Scenarios] {-}

[Mandatory.
Title can vary.
Tables or figures can be used as necessary to support decision-making.]

### Ecosystem and Climate Change Considerations {-}

[Mandatory.
Maximum 300 words.
May be moved earlier in the Assessment section.]

### Harvest Decision Rule Outputs {-}

[If applicable (otherwise, do not include).] 

### Evaluation of Exceptional Circumstances/Assessment Triggers {-}

[If applicable (otherwise, do not include).] 
